[tool.flake8]
ignore = "E203,E266,H106,H904,E133"
max-complexity = 25
hang-closing = true
max-doc-length = 88
max-line-length = 88
per-file-ignores = '*/__init__.py:F401'

[tool.black]
line-length = 88
target-version = ['py36']

[tool.isort]
line_length = 88
profile = "black"
multi_line_output = 3
py_version = 27
